/**
* Generated by pullcode v1.1.8.
* Don't edit!
*
* @module Model-group-controller
*/
import { CreateAxiosOptions } from "pullcode/src/httputil/axiosTransform";
import BizService from "./BizService";
import type {
  CmdbModelGroupDto,
  Response,
} from "./types"

export class ModelService extends BizService {

  constructor(options?: Partial<CreateAxiosOptions>) {
    super(options);
  }

  /**
  * POST /model/group/add
  *
  * @param payload 
  * @returns Promise<Response> OK
  */
  postModelGroupAdd(
    payload: CmdbModelGroupDto,
  ): Promise<Response> {
      return this.getAxios().post(`/model/group/add`,
          payload,
          {
          }
        )
  }

  /**
  * GET /model/group/list
  *
  * @returns Promise<Response> OK
  */
  getModelGroupList(
  ): Promise<Response> {
      return this.getAxios().get(`/model/group/list`,
          {
          }
        )
  }

}

export default ModelService;
  
export function createModelService(opt?: Partial<CreateAxiosOptions>) {
  return new ModelService(opt);
}

export const modelService = createModelService();

