/**
* Generated by pullcode v1.1.5.
* You can edit it as your need.
*/
import { merge } from 'lodash-es';
import { CreateAxiosOptions, VAxios } from 'pullcode/src/httputil/Axios';
import { RequestOptions } from 'pullcode/src/types/axios';

const defaultOptions: CreateAxiosOptions = {
  requestOptions: {
    apiUrl: 'https://petstore3.swagger.io/api/v3', // same as baseUrl
    urlPrefix: '',
  } as RequestOptions,
}

export class BizService extends VAxios {
  constructor(options?: Partial<CreateAxiosOptions>) {
    const opt = merge(defaultOptions, options || {})
    super(opt);
  }
}

export default BizService;

