/* eslint-disable prettier/prettier */
/**
 * Generated by pullcode v1.2.1.
 * You can edit it as your need.
 */
import { merge } from "lodash-es";
import { CreateAxiosOptions, VAxios } from "pullcode/dist/esm/httputil/Axios";
import { RequestOptions } from "pullcode/dist/esm/types/axios";

const defaultOptions: CreateAxiosOptions = {
  requestOptions: {
    apiUrl: 'https://petstore3.swagger.io/api/v3', // same as baseUrl
    urlPrefix: '',
  } as RequestOptions,
};

export class BizService extends VAxios {
  constructor(options?: Partial<CreateAxiosOptions>) {
    super(merge(defaultOptions, options || {}));
  }
}

export default BizService;
