/* eslint-disable prettier/prettier */
/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Generated by pullcode v1.2.1.
 * Don't edit!
 *
 * @module Conversion
 */
import { CreateAxiosOptions } from "pullcode/src/httputil/axiosTransform";
import BizService from "./BizService";
import type { GetConversionFailedExceptionResp } from "./types";

export class ConversionService extends BizService {
  constructor(options?: Partial<CreateAxiosOptions>) {
    super(options);
  }

  /**
   * GET /conversion/failed/exception
   *
   * @returns Promise<GetConversionFailedExceptionResp>
   */
  getConversionFailedException(): Promise<GetConversionFailedExceptionResp> {
    return this.getAxios().get(`/conversion/failed/exception`, {});
  }
}

export default ConversionService;

export function createConversionService(opt?: Partial<CreateAxiosOptions>) {
  return new ConversionService(opt);
}

export const conversionService = createConversionService();
