/* eslint-disable prettier/prettier */
/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable @typescript-eslint/no-empty-interface */
/**
 * Generated by pullcode v1.2.1.
 * Don't edit!
 *
 * @module types
 */

export interface GetBookNotFoundExceptionResp {}

export interface GetBookPageResp {}

export interface GetConversionFailedExceptionResp {}

export interface Order {
  col: string;
  sort: string;
}

export interface Page {
  filter: PageFilter;
  /**
   * 排序规则
   */
  orders: Order[];
  /**
   * 页码
   */
  pageNo: number;
  /**
   * 每页行数
   */
  size: number;
}

export interface PageFilter {
  bookName: string;
  bookShelf: number;
}

/**
 * 分页筛选条件
 */
export interface PageQuery {
  filter: PageFilter;
  page: Page;
}

export interface PageRet {
  hasNext: boolean;
  items: any;
  pageNo: number;
  pageSize: number;
  total: number;
}

export interface PostBookPageReq {
  author: string;
  name: string;
}

export interface PostBookPageResp {}
